### ISSUE TITLE
Docker image in dockerhub

### ISSUE THREAD

**Issue by 7Cornelio** [mosquito/pypi-server#23]
It seems that the docker image in Dockerhub is broken:

```
$ docker run -e DB=mysql://xxxx:zzzzz@host/database -e PORT=8080 -p 8080:8080 mosquito/pypi-server:0.4.7
Traceback (most recent call last):
  File "/usr/bin/pypi-server", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Cloning the repo and running a rebuilt docker image is fine, though.

**Comment by mosquito** [comment]
Sorry for this. This is already fixed. But you have to update `mosquito/pypi-server:0.4.7` local docker image.
