### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by trondhindenes** [mosquito/pypi-server#24]
I've successfully uploaded a package, but I can't pip install it. I'm using:
`pip3 install mypackage -i https://myserver.domain.com/pypi --verbose` and can see that pip is getting a 404 back.

I can see in the pypi-server logs that it logs a 404 when I attempt to install a package.

I'm not too familiar with the intricasies of pip, but shouldn't this work?

**Comment by mosquito** [comment]
`/pypi` is an rpc endpoint. For retreiving any package use the `/simple/` endpoint.

**Comment by trondhindenes** [comment]
Thanks! Might be something to include in the readme.

**Comment by mosquito** [comment]
May be. But it's standard paths for global pypi.
