### ISSUE TITLE
XML-RPC error with new pypi-server

### ISSUE THREAD

**Issue by kdart** [mosquito/pypi-server#43]
Hello!

I've just recently installed the pypi-server for in-house use. When I try to use it from the pip client, I get this from the client:

> pip search -i myserver mypackage

> ERROR: Exception:
> Traceback (most recent call last):
>   File "/home/keith.dart/venvs/ouster_test/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
>     status = self.run(options, args)
>   File "/home/keith.dart/venvs/ouster_test/lib/python3.6/site-packages/pip/_internal/commands/search.py", line 48, in run
>     pypi_hits = self.search(query, options)
>   File "/home/keith.dart/venvs/ouster_test/lib/python3.6/site-packages/pip/_internal/commands/search.py", line 64, in search
>     pypi = xmlrpc_client.ServerProxy(index_url, transport)
>   File "/usr/lib/python3.6/xmlrpc/client.py", line 1418, in __init__
>     raise OSError("unsupported XML-RPC protocol")
> OSError: unsupported XML-RPC protocol

Any suggestions on how to fix this?

**Comment by mosquito** [comment]
I guess you should pass correct pypi-URL


Just run:

```bash
$ docker run --rm -it -p 8080:80 mosquito/pypi-server:latest
```

and try to search with:

```bash
$ pip3.7 --version
pip 19.1.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)

$ pip3.7 search -i http://127.0.0.1:8080/simple/ pypi-server | head -n 2
pypi-server (0.4.8)                  - Tornado PyPi server
pypi-publisher (0.0.4)               - A cli for publishing packages to pypi, without the hassle
```

**Comment by kdart** [comment]
Thanks for the help! It does seem to be a client issue. If I use the the URL on the command line it does work. But if I try to use the .pypirc file and the short name I get that error.
