### ISSUE TITLE
Cannot upload package

### ISSUE THREAD

**Issue by CatsNipYummy** [mosquito/pypi-server#49]
I've seen related issues #17 and #25 but I recently upgraded the system to Ubuntu 19.10 and have a docker of the pypi-server running. For some reason I cant upload to it anymore. It was working fine before. I get the following error:

HTTPError: 405 Client Error: Method Not Allowed for url: http://192.168.57.114:5556/

My server forwards to port 5556.

This is what my ~/.pypirc looks like:

```
[distutils]
index-servers =
    mypypi

[mypypi]
repository=http://192.168.57.114:5556/pypi
username=my_username
password=my_password
```

Am I missing something here?

**Comment by CatsNipYummy** [comment]
Any updates? Am I the only one facing this issue? I tried running it on 18.04 on another machine. Facing the same issue.

**Comment by mosquito** [comment]
Hello @CatsNipYummy sorry for the delay, your issue has been closed by you. Did you find the solution?

**Comment by CatsNipYummy** [comment]
@mosquito i opened a new one. I want to know if there’s a size limitation on the upload. #50
